### ISSUE TITLE
Crash when trying to connect (with default and modded)

### ISSUE THREAD

**Issue by kingoscargames** [Sirvoid/Sirvoid-s-Survival-Test-CC-Patch-DX#1]
=== crash occurred ===
Time: 4-8-2017 20:50:15
Running on: .NET 2.0.50727.8784, Windows - 6.2.9200.0
System.IndexOutOfRangeException: De index ligt buiten de matrixgrenzen.
   bij ClassicalSharp.Network.Protocols.ClassicProtocol.loadinventory()
   bij ClassicalSharp.Network.NetworkProcessor.ReadPacket(Byte opcode)
   bij ClassicalSharp.Network.NetworkProcessor.Tick(ScheduledTask task)
   bij ClassicalSharp.Game.DoScheduledTasks(Double time)
   bij ClassicalSharp.Game.RenderFrame(Double delta)
   bij ClassicalSharp.DesktopWindow.OnRenderFrame(FrameEventArgs e)
   bij OpenTK.GameWindow.RaiseRenderFrame(Stopwatch render_watch, Double& next_render, FrameEventArgs render_args)
   bij OpenTK.GameWindow.Run()
   bij ClassicalSharp.Program.RunMultiplayer(String[] args, Boolean nullContext, Int32 width, Int32 height)
   bij ClassicalSharp.Program.Main(String[] args)

-- Using Direct3D9 api --
Adapter: Intel(R) HD Graphics 520
Mode: HardwareVertexProcessing
Texture memory: 4093 MB
Max 2D texture dimensions: 8192
Depth buffer format: D24X8
Back buffer format: X8R8G8B8

**Comment by Sirvoid** [comment]
I found a big issue with the inventory :s 

I quickly fixed your inventory for the moment but I need to fix that.

**Comment by Sirvoid** [comment]
Fixed.
